#!/bin/bash

export RUN_PATH=`dirname $0`

((

if [ "$EUID" -ne 0 ]; then
  echo "[!] Please run as root or use sudo!"
  exit 1
fi

$RUN_PATH/bin/terraform init
STATUS=`echo $?`
if [ "$STATUS" != 0 ]; then
  echo "[!] ERROR: Terraform initialization failed!"
  exit 1
fi
$RUN_PATH/bin/terraform apply
STATUS=`echo $?`
if [ "$STATUS" != 0 ]; then
  echo "[!] ERROR: Server installation failed!"
  exit 1
fi

echo "[*] Installation finished!"

) 2>&1) | tee $RUN_PATH/log.out
