# AUTO GENERATED FILE. DO NOT EDIT THIS FILE!

subnet DHCPD_SUBNET netmask DHCPD_NETMASK {
    next-server DHCPD_TFTP_SERVER_ADDRESS;

    option subnet-mask DHCPD_NETMASK;
    option routers DHCPD_DEFAULT_GATEWAY;
    min-lease-time 1200;
    default-lease-time 1800;
    max-lease-time 3600;

    host node.controller {
        hardware ethernet DHCPD_CONTROLLER_MAC_ADDRESS;
        fixed-address DHCPD_CONTROLLER_INTERNAL_IP;
        filename "DHCPD_PXE_PATH_CONTROLLER";
    }

    host node.compute1 {
        hardware ethernet DHCPD_COMPUTE1_MAC_ADDRESS;
        fixed-address DHCPD_COMPUTE1_INTERNAL_IP;
        filename "DHCPD_PXE_PATH_COMPUTE1";
    }

    host node.compute2 {
        hardware ethernet DHCPD_COMPUTE2_MAC_ADDRESS;
        fixed-address DHCPD_COMPUTE2_INTERNAL_IP;
        filename "DHCPD_PXE_PATH_COMPUTE2";
    }
}
